[build]
publish = "dist"
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
NODE_OPTIONS = "--max_old_space_size=4096"

# SPA를 위한 리다이렉트 설정
[[redirects]]
from = "/*"
to = "/index.html"
status = 200