[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

# SPA를 위한 리다이렉트 설정
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 헤더 설정 (보안 및 CORS)
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"